// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// htdpinit
void htdpinit();
RcppExport SEXP htdp_htdpinit() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    htdpinit();
    return R_NilValue;
END_RCPP
}
// displace
DataFrame displace(NumericMatrix xy, Date t0, Date t1, int iopt);
RcppExport SEXP htdp_displace(SEXP xySEXP, SEXP t0SEXP, SEXP t1SEXP, SEXP ioptSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type xy(xySEXP);
    Rcpp::traits::input_parameter< Date >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< Date >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< int >::type iopt(ioptSEXP);
    __result = Rcpp::wrap(displace(xy, t0, t1, iopt));
    return __result;
END_RCPP
}
