# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.htdpinit <- function() {
    invisible(.Call('htdp_htdpinit', PACKAGE = 'htdp'))
}

displacement <- function(xy, start, end, iopt) {
    .Call('htdp_displacement', PACKAGE = 'htdp', xy, start, end, iopt)
}

